defmodule S02Transformer.Repo.Migrations.InitialSpike do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cpy_company, primary_key: false) do
      add(:cpy_id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:cpy_org_id, :uuid, null: false)
      add(:cpy_slug, :text, null: false)
      add(:cpy_name, :text)
    end

    create(
      unique_index(:cpy_company, [:cpy_org_id, :cpy_slug],
        name: "cpy_company_unique_slug_per_org_index"
      )
    )

    create table(:com_contact, primary_key: false) do
      add(:com_id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:com_name, :text)
      add(:com_org_id, :uuid, null: false)

      add(
        :com_company_id,
        references(:cpy_company,
          column: :cpy_id,
          name: "com_contact_com_company_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:com_contact, "com_contact_com_company_id_fkey"))

    drop(table(:com_contact))

    drop_if_exists(
      unique_index(:cpy_company, [:cpy_org_id, :cpy_slug],
        name: "cpy_company_unique_slug_per_org_index"
      )
    )

    drop(table(:cpy_company))
  end
end
