defmodule SamenCore.TestRepo.Migrations.VaultTokenColumns do
  @moduledoc """
  Gate-0 vault-stack fix (P0 correctness): convert the vault-routed PII columns
  from plaintext storage (`:map` for composites, `:date` for scalar dob) to
  `:text` TOKEN columns. After this migration the domain column holds a `vt_*`
  token (`Samen.Type.VaultField`), never plaintext — the plaintext ciphertext
  lives per-subject-encrypted in `pii_vault`. `Samen.Vault.Change` writes the
  token; `Samen.Type.VaultField.cast_stored/2` presents `%Masked{}` on read.

  Autogenerated with `mix ash.codegen vault_token_columns`, reviewed by hand.
  """

  use Ecto.Migration

  def up do
    alter table(:stf_staff) do
      modify(:stf_phones, :text)
      modify(:stf_emails, :text)
      modify(:stf_full_name, :text)
    end

    alter table(:pat_patient) do
      modify(:pat_phones, :text)
      modify(:pat_emails, :text)
      modify(:pat_full_name, :text)
      modify(:pii_pat_dob, :text)
    end
  end

  def down do
    alter table(:pat_patient) do
      modify(:pii_pat_dob, :date)
      modify(:pat_full_name, :map)
      modify(:pat_emails, :map)
      modify(:pat_phones, :map)
    end

    alter table(:stf_staff) do
      modify(:stf_full_name, :map)
      modify(:stf_emails, :map)
      modify(:stf_phones, :map)
    end
  end
end
