defmodule SamenCore.TestRepo.Migrations.NotificationPreferenceDigestCadence do
  @moduledoc """
  C8 (T30): adds `nep_digest_cadence` / `nep_digest_timezone` to the
  `nep_notification_preference` fixture table
  (`SamenCore.Support.NotificationFixture.NotificationPreference`, generated by
  `Samen.Scopes.Primitives.Blueprint.define_notification_preference/5`). Plain
  additive columns with defaults — no `catalog_sync` needed (the
  `add_org_onboarded_at` / `add_send_provider_message_id` precedent).
  """
  use Ecto.Migration

  def up do
    alter table(:nep_notification_preference) do
      add(:nep_digest_cadence, :text, null: false, default: "daily")
      add(:nep_digest_timezone, :text, null: false, default: "Etc/UTC")
      add(:nep_digest_last_sent_at, :utc_datetime)
    end
  end

  def down do
    alter table(:nep_notification_preference) do
      remove(:nep_digest_cadence)
      remove(:nep_digest_timezone)
      remove(:nep_digest_last_sent_at)
    end
  end
end
