defmodule SamenCore.TestRepo.Migrations.InitialCore do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stf_staff, primary_key: false) do
      add(:stf_license_no, :text)
      add(:stf_job_title, :text)
      add(:stf_full_name, :map)
      add(:stf_emails, :map)
      add(:stf_phones, :map)
      add(:stf_id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:stf_org_id, :uuid, null: false)
      add(:stf_inserted_at, :utc_datetime, null: false)
      add(:stf_updated_at, :utc_datetime, null: false)
    end

    create table(:prp_fixture, primary_key: false) do
      add(:prp_name, :text)
      add(:prp_label, :text)
      add(:prp_notes, :text)
      add(:prp_id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:prp_org_id, :uuid, null: false)
      add(:prp_inserted_at, :utc_datetime, null: false)
      add(:prp_updated_at, :utc_datetime, null: false)
    end

    create table(:pat_patient, primary_key: false) do
      add(:pat_consent_on_file, :boolean, default: false)
      add(:pat_job_title, :text)
      add(:pii_pat_dob, :date)
      add(:pii_pat_mrn, :text)
      add(:pat_full_name, :map)
      add(:pat_emails, :map)
      add(:pat_phones, :map)

      add(
        :pat_primary_provider_id,
        references(:stf_staff,
          column: :stf_id,
          name: "pat_patient_pat_primary_provider_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(:pat_id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:pat_org_id, :uuid, null: false)
      add(:pat_inserted_at, :utc_datetime, null: false)
      add(:pat_updated_at, :utc_datetime, null: false)
    end

    create table(:cpy_company, primary_key: false) do
      add(:cpy_name, :text, null: false)
      add(:cpy_id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:cpy_org_id, :uuid, null: false)
      add(:cpy_inserted_at, :utc_datetime, null: false)
      add(:cpy_updated_at, :utc_datetime, null: false)
    end

    create table(:com_contact, primary_key: false) do
      add(:com_name, :text, null: false)

      add(
        :com_company_id,
        references(:cpy_company,
          column: :cpy_id,
          name: "com_contact_com_company_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(:com_id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:com_org_id, :uuid, null: false)
      add(:com_inserted_at, :utc_datetime, null: false)
      add(:com_updated_at, :utc_datetime, null: false)
    end
  end

  def down do
    drop(constraint(:com_contact, "com_contact_com_company_id_fkey"))

    drop(table(:com_contact))

    drop(table(:cpy_company))

    drop(constraint(:pat_patient, "pat_patient_pat_primary_provider_id_fkey"))

    drop(table(:pat_patient))

    drop(table(:prp_fixture))

    drop(table(:stf_staff))
  end
end
