defmodule Samenerp.Cms do
  @moduledoc """
  Samenerp's CMS domain — mounts the framework `Samen.Scopes.Cms` blueprint
  (ADR-004; T3.5), the same one-line adoption `Demo.CmsScope` ships.

  Phase 5 mounts this for ONE reason: a helpdesk knowledge-base article IS a CMS
  `Post` (`Samen.Web.Support.KbReads` never defines a parallel article resource —
  `visibility: :public` + `status: :published` is the entire delta that turns a
  post into a portal-visible KB article). The `:kb` portal route and the agent
  KB surface both read this namespace, so the KB module group is unmountable
  without it.

  One `use Samen.Scopes.Cms` expands into six host-owned resources in this
  namespace:

    * `Samenerp.Cms.Page`       — a published page (draft→publish workflow)
    * `Samenerp.Cms.Post`       — a blog post / KB article (draft→publish +
      `visibility` internal|public)
    * `Samenerp.Cms.Block`      — a reusable content block (component/fragment)
    * `Samenerp.Cms.Media`      — a media asset (image/video/document reference)
    * `Samenerp.Cms.Navigation` — Tier-0 config rows (nav items per org)
    * `Samenerp.Cms.SeoMeta`    — SEO metadata attached to a page or post

  plus the three E7 `versioned: :snapshot` history resources
  (`Samenerp.Cms.{Page,Post,Block}.Version`, generated by ash_paper_trail per
  ADR-040 §6.5) — real domain members that must be registered.

  ## Abbrevs (permanent, allocator-reserved)

  Each resource carries a permanent 3-letter abbrev, reserved through the
  sanctioned allocator (`mix samen.abbrev.reserve`, ADR-023) under host
  `samenerp` — this module never invents or hand-edits a registry row:

    * `Samenerp.Cms.Page`           → `scg`  (`Page.Version`  → `spv`)
    * `Samenerp.Cms.Post`           → `sct`  (`Post.Version`  → `stv`)
    * `Samenerp.Cms.Block`          → `scb`  (`Block.Version` → `sbv`)
    * `Samenerp.Cms.Media`          → `scd`
    * `Samenerp.Cms.Navigation`     → `scn`
    * `Samenerp.Cms.SeoMeta`        → `scf`

  Only the six base abbrevs are literals here (the macro's `abbrevs:` override);
  the three `<Resource>.Version` abbrevs are injected into the generated modules
  from the registry at build time and are deliberately NOT pinned in code
  (ADR-023 §6.2).

  ## Non-PII

  The CMS scope has no 🔒 objects — every field is authored content, not subject
  identity data (`title`, `body`, `slug`, `description`, `alt_text`, `label` are
  all product copy). No vault routing, no masking surface.
  """

  use Ash.Domain, validate_config_inclusion?: false

  use Samen.Scopes.Cms,
    otp_app: :samenerp,
    repo: Samenerp.Repo,
    namespace: Samenerp.Cms,
    abbrevs: %{
      page: "scg",
      post: "sct",
      block: "scb",
      media: "scd",
      navigation: "scn",
      seo_meta: "scf"
    }
end
