defmodule S03Fragments.Repo.Migrations.InitialSpike do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stf_staff, primary_key: false) do
      add(:stf_id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:stf_org_id, :uuid, null: false)
      add(:stf_license_no, :text)
      add(:stf_job_title, :text)
      add(:stf_custom, :map)
      add(:stf_full_name, :text)
      add(:stf_emails, :text)
      add(:stf_phones, :text)
    end

    create table(:pat_patient, primary_key: false) do
      add(:pat_id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:pat_org_id, :uuid, null: false)
      add(:pat_consent_on_file, :boolean, default: false)
      add(:pat_job_title, :text)
      add(:pat_custom, :map)
      add(:pat_dob, :date)
      add(:pat_mrn, :text)
      add(:pat_full_name, :text)
      add(:pat_emails, :text)
      add(:pat_phones, :text)

      add(
        :pat_primary_provider_id,
        references(:stf_staff,
          column: :stf_id,
          name: "pat_patient_pat_primary_provider_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:pat_patient, "pat_patient_pat_primary_provider_id_fkey"))

    drop(table(:pat_patient))

    drop(table(:stf_staff))
  end
end
